### ISSUE TITLE
Typescript definitions

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#515]
## Problem

At the moment you can install Typescript 2.0 definitions via `npm install @types/turf`.

However, not all of the definitions are defined and it can be overwhelming trying to manage a [1280+ LOC type definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/turf/turf.d.ts).

## Solution

I'm suggesting we host the Typescript type definitions within the Turf library instead of [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/turf).

By including a simple & minimalistic `index.d.ts` and `test/types.ts` within each package, the type definitions will be bundled with each namespace package.

By default `index.d.ts` will be automatically detected, however including `"types": "index.d.ts"` in the `package.json` is a good practice.

```javascript
/// <reference types="geojson" />

/***
 * http://turfjs.org/docs/#point
 */
export type Point = Array<number>
export function point(coordinates: Point, properties?: Object): GeoJSON.Feature<GeoJSON.Point>;
```

## To-Do

- [x] [`turf-along`](https://github.com/Turfjs/turf/blob/master/packages/turf-along/index.d.ts)
- [x] `turf-area`
- [x] [`turf-bbox`](https://github.com/Turfjs/turf/tree/master/packages/turf-bbox/index.d.ts)
- [x] `turf-bbox-polygon`
- [x] `turf-bearing`
- [x] `turf-bezier`
- [x] `turf-buffer`
- [x] `turf-center`
- [x] `turf-center-of-mass`
- [x] `turf-centroid`
- [x] [`turf-circle`](https://github.com/Turfjs/turf/tree/master/packages/turf-circle/index.d.ts)
- [x] `turf-collect`
- [x] `turf-combine`
- [x] `turf-concave`
- [x] `turf-convex`
- [x] `turf-destination`
- [x] `turf-difference`
- [x] `turf-distance`
- [x] `turf-envelope`
- [x] `turf-explode`
- [x] `turf-flip`
- [x] [`turf-helpers`](https://github.com/Turfjs/turf/blob/master/packages/turf-helpers/index.d.ts)
- [x] `turf-hex-grid`
- [x] `turf-idw`
- [x] `turf-inside`
- [x] `turf-intersect`
- [x] `turf-invariant`
- [x] `turf-isolines`
- [x] `turf-kinks`
- [x] `turf-line-distance`
- [x] `turf-line-slice`
- [x] `turf-line-slice-along`
- [x] `turf-meta`
- [x] `turf-midpoint`
- [x] `turf-nearest`
- [x] `turf-planepoint`
- [x] `turf-point-grid`
- [x] `turf-point-on-line`
- [x] `turf-point-on-surface`
- [x] `turf-random`
- [x] `turf-sample`
- [x] `turf-simplify`
- [x] `turf-square`
- [x] `turf-square-grid`
- [x] `turf-tag`
- [x] `turf-tesselate`
- [x] `turf-tin`
- [x] `turf-triangle-grid`
- [x] `turf-union`
- [x] `turf-within`

**Comment by DenisCarriere** [comment]
@tmcw @morganherlocker Good news! With the latest update `3.6.1` the typescript definitions are working for `@turf/helpers` without any additional custom Typescript installs.

After this is done... Implementing this for `Flow` should be easy enough since both of them have a very similar syntax, only need to add a `.flowconfig` or add the flow syntax directly in the source code.

![image](https://cloud.githubusercontent.com/assets/550895/20545224/016f6758-b0dc-11e6-8729-3a7e82177e99.png)

```json
{
  "name": "test",
  "main": "index.js",
  "dependencies": {
    "@turf/helpers": "^3.6.1"
  }
}
```

**Comment by DenisCarriere** [comment]
🚀🚀 Woot! Completed all the Typescript definitions

```
packages/turf-along/index.d.ts
packages/turf-area/index.d.ts
packages/turf-bbox-polygon/index.d.ts
packages/turf-bbox/index.d.ts
packages/turf-bearing/index.d.ts
packages/turf-bezier/index.d.ts
packages/turf-buffer/index.d.ts
packages/turf-center-of-mass/index.d.ts
packages/turf-center/index.d.ts
packages/turf-centroid/index.d.ts
packages/turf-circle/index.d.ts
packages/turf-collect/index.d.ts
packages/turf-combine/index.d.ts
packages/turf-concave/index.d.ts
packages/turf-convex/index.d.ts
packages/turf-destination/index.d.ts
packages/turf-difference/index.d.ts
packages/turf-distance/index.d.ts
packages/turf-envelope/index.d.ts
packages/turf-explode/index.d.ts
packages/turf-flip/index.d.ts
packages/turf-helpers/index.d.ts
packages/turf-hex-grid/index.d.ts
packages/turf-idw/index.d.ts
packages/turf-inside/index.d.ts
packages/turf-intersect/index.d.ts
packages/turf-invariant/index.d.ts
packages/turf-isolines/index.d.ts
packages/turf-kinks/index.d.ts
packages/turf-line-distance/index.d.ts
packages/turf-line-slice-along/index.d.ts
packages/turf-line-slice/index.d.ts
packages/turf-meta/index.d.ts
packages/turf-midpoint/index.d.ts
packages/turf-nearest/index.d.ts
packages/turf-planepoint/index.d.ts
packages/turf-point-grid/index.d.ts
packages/turf-point-on-line/index.d.ts
packages/turf-point-on-surface/index.d.ts
packages/turf-random/index.d.ts
packages/turf-sample/index.d.ts
packages/turf-simplify/index.d.ts
packages/turf-square-grid/index.d.ts
packages/turf-square/index.d.ts
packages/turf-tag/index.d.ts
packages/turf-tesselate/index.d.ts
packages/turf-tin/index.d.ts
packages/turf-triangle-grid/index.d.ts
packages/turf-union/index.d.ts
packages/turf-within/index.d.ts
```

**Comment by morganherlocker** [comment]
Nice work!

**Comment by DenisCarriere** [comment]
Thanks! Should be good to publish to npm, test it out before, but so far the typescript definitions are working in my environment.

**Comment by DenisCarriere** [comment]
@morganherlocker @tmcw Just published a new version to npm `3.6.3` with all of these changes.

One minor hiccup is I forgot to include `"types": "index.d.ts"` in the package.json, I thought it was optional, without it it doesn't detect the Typescript definition file.

I hope you don't mind me pushing another release to `3.6.4` in the same day, I'll do the appropriate changes to the `package.json`'s and wait for an answer before I publish another release.

**Comment by nicolasca** [comment]
Hey,

I don't see anymore index.d.ts for the centroid package. Is this a missing ?

**Comment by geirsagberg** [comment]
Seems to be missing for @turf/distance as well.

**Comment by wafisher** [comment]
How are we supposed to use types? I have the following, but WebStorm/IntelliJ doesn't automatically see these types (why?) so I wonder if I'm doing something wrong.

```
# MyFile.tsx
import * as turf from '@turf/turf'
import { Point, Feature, Properties } from '@turf/turf'

export function simpleFn(lat: number, long: number, properties: Properties): Feature<Point> {
    return turf.point([long, lat], properties)
}
```

**Comment by sgarwood** [comment]
> How are we supposed to use types? I have the following, but WebStorm/IntelliJ doesn't automatically see these types (why?) so I wonder if I'm doing something wrong.
> 
> ```
> # MyFile.tsx
> import * as turf from '@turf/turf'
> import { Point, Feature, Properties } from '@turf/turf'
> 
> export function simpleFn(lat: number, long: number, properties: Properties): Feature<Point> {
>     return turf.point([long, lat], properties)
> }
> ```

Try removing `@types/turf` if you have it in your `package.json` file if you have it

**Comment by bockoblur** [comment]
> I don't see anymore index.d.ts for the centroid package. Is this a missing ?

Any news on this? Just installed @turf/centroid 6.0.1 and types are missing…

**Comment by onsah** [comment]
It is also missing from @turf/center-of-mass package

**Comment by soosgyul** [comment]
> > I don't see anymore index.d.ts for the centroid package. Is this a missing ?
> 
> Any news on this? Just installed @turf/centroid 6.0.1 and types are missing…

I came around this, by importing this:
`import centroid from "@turf/centroid";
import * as turf from "@turf/helpers";
import { Feature, Point } from "@turf/helpers";`
and then
`let center: Feature<Point> = centroid(pol);`

**Comment by mfedderly** [comment]
If you use 6.2.0-alpha.3 the types and versions are all consistent. I'm working on getting 6.2.0 stable but its definitely worth checking out if you want tree shaking, consistent package dependencies, and typescript definitions.

**Comment by soosgyul** [comment]
> If you use 6.2.0-alpha.3 the types and versions are all consistent. I'm working on getting 6.2.0 stable but its definitely worth checking out if you want tree shaking, consistent package dependencies, and typescript definitions.

ok. thanks. Do you have a rough estimate on a stable release?

**Comment by mfedderly** [comment]
I'm hoping to maybe get it done by end of year but the timeline is not completely set. 6.2.0-alpha.3 should be usable if you give it a try and test it a little bit. I have been using -alpha2 successfully for a few months.
