### ISSUE TITLE
Add Geometry & GeometryCollection support to @turf/truncate

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#676]
Add every GeoJSON type to [`@turf/truncate`](https://github.com/Turfjs/turf/tree/master/packages/turf-truncate).
- [x] `Feature<any>`
- [x] `FeatureCollection<any>`
- [x] [`Geometry`](http://geojson.org/geojson-spec.html#appendix-a-geometry-examples)
- [x] [`GeometryCollection`](http://geojson.org/geojson-spec.html#geometrycollection)

**ToDo**
- [x] Add new fixtures to [`/test/in`](https://github.com/Turfjs/turf/tree/master/packages/turf-truncate/test/in)
- [x] Update Typescript definition [`index.d.ts`](https://github.com/Turfjs/turf/blob/master/packages/turf-truncate/index.d.ts)

**Comment by DenisCarriere** [comment]
Added via PR https://github.com/Turfjs/turf/issues/677
