### ISSUE TITLE
New Module proposal `@turf/boolean-point-on-line`

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#809]
## New Module `@turf/boolean-point-on-line`

A few of the `boolean` modules have been using `isPointOnLineSegment`. Would be nice to extract this useful method and have it's own dedicated module with it's own dedicated tests.

## To-Do
- [x] Add method as TurfJS module
- [x] Add tests
- [x] Support LineString and LineSegment (2 vertex LineString).
- [x] **Optional**: MultiLineString support

## Current Method

```javascript
/**
 * Is a point on a line segment
 * Only takes into account outer rings
 * See http://stackoverflow.com/a/4833823/1979085
 *
 * @private
 * @param {[number, number]} lineSegmentStart coord pair of start of line
 * @param {[number, number]} lineSegmentEnd coord pair of end of line
 * @param {[number, number]} point coord pair of point to check
 * @param {Boolean} incEnd whether the point is allowed to fall on the line ends
 * @returns {Boolean} true/false
 */
function isPointOnLineSegment(lineSegmentStart, lineSegmentEnd, point, incEnd) {
    var dxc = point[0] - lineSegmentStart[0];
    var dyc = point[1] - lineSegmentStart[1];
    var dxl = lineSegmentEnd[0] - lineSegmentStart[0];
    var dyl = lineSegmentEnd[1] - lineSegmentStart[1];
    var cross = dxc * dyl - dyc * dxl;
    if (cross !== 0) {
        return false;
    }
    if (incEnd) {
        if (Math.abs(dxl) >= Math.abs(dyl)) {
            return dxl > 0 ? lineSegmentStart[0] <= point[0] && point[0] <= lineSegmentEnd[0] : lineSegmentEnd[0] <= point[0] && point[0] <= lineSegmentStart[0];
        }
        return dyl > 0 ? lineSegmentStart[1] <= point[1] && point[1] <= lineSegmentEnd[1] : lineSegmentEnd[1] <= point[1] && point[1] <= lineSegmentStart[1];
    } else {
        if (Math.abs(dxl) >= Math.abs(dyl)) {
            return dxl > 0 ? lineSegmentStart[0] < point[0] && point[0] < lineSegmentEnd[0] : lineSegmentEnd[0] < point[0] && point[0] < lineSegmentStart[0];
        }
        return dyl > 0 ? lineSegmentStart[1] < point[1] && point[1] < lineSegmentEnd[1] : lineSegmentEnd[1] < point[1] && point[1] < lineSegmentStart[1];
    }
}
```

**Comment by stebogit** [comment]
Implemented with #858
