### ISSUE TITLE
Cluster modules - New modules/features

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#845]
# Cluster Modules/Features

The past few cluster related modules have helped us define some of the "nice to have" features related to GeoJSON clustering. I propose we start a collection of `clusters-<name>` modules for specific clustering algorithms (mainly focusing on the GeoJSON implementation & leveraging an external dependency for the algorithm) and use `@turf/clusters` as a utility module for common clustering methods & operations:

- [x] `@turf/clusters-kmean` https://github.com/Turfjs/turf/pull/787 (Algorithm dependency [`skmeans`](https://github.com/solzimer/skmeans))
- [x] `@turf/clusters-dbscan`https://github.com/Turfjs/turf/pull/812   (Algorithm dependency [`density-clustering`](https://github.com/uhho/density-clustering))
- [x] `@turf/clusters` https://github.com/Turfjs/turf/issues/841 (only TurfJS dependencies)
  - [x] `getCluster`
  - [x] `clusterEach`
  - [x] `clusterReduce`

## To-Do
- [x] Rename `@turf/clusters` => `@turf/clusters-kmeans`
- [x] Add deprecated warning message to `@turf/clusters` in favor of using `@turf/clusters-kmeans` (~major release `v5.0` calling it the Cluster Release~ `@turf/clusters` was never actually published to `v4.5.0`, going to bump this change to `v4.6.0`)
- [x] ~Rename `@turf/clusters-dbscan` => `@turf/cluster-dbscan`~
- [ ] ~(**Optional**)~ Change output of `@turf/clusters-kmeans` to pure GeoJSON output `FeatureCollection<Point>` (each feature will still include `cluster` property) in favor of leveraging the `@turf/clusters` utility tools to generate derived centroids and/or concave polygons.

So far it's been @stebogit & @DenisCarriere driving the direction of these `clusters` modules, however I would love to hear some feedback from @Turfjs/ownership before we publish the next release of these cluster modules.

> EDIT: Changed `cluster` => `clusters` (plural module name to prevent any accidental conflicts with `cluster` property).

**Comment by DenisCarriere** [comment]
@stebogit Ok finished adding all `@turf/clusters` methods (`getCluster`, `clusterEach`, `clusterReduce`). Looking forward to your feedback (no rush)

**Comment by stebogit** [comment]
Implemented with PR #847

**Comment by DenisCarriere** [comment]
Woot! All done! Definitely open to suggestions for new features in `@turf/clusters`, those 3 methods was just to get something started.
