### ISSUE TITLE
Test @example in TurfJS core

### ISSUE THREAD

**Issue by DenisCarriere** [Turfjs/turf#859]
# Test `@example` in TurfJS core
Going to start testing the `@example` directly in TurfJS core, that way we don't have  switch back and forth between `turf-www` & `turf`. Used/updated the existing code that was being used in [`turf-www/test/build.js`](https://github.com/Turfjs/turf-www/blob/gh-pages/test/build.js).

## How to use

```
$ cd turf/packages/turf
$ npm test
$ node test.example.js
```

## To-Do
- [x] Fix @example errors
> Quite a few already - can use this PR https://github.com/Turfjs/turf/pull/857
- [x] Include `addToMap` validation tests - https://github.com/Turfjs/turf-www/issues/113#issuecomment-317167454
- [x] Add `node test.example` in `package.json` => `scripts` => `posttest`
> once all the errors are fixed
- [x] Add DocumentationJS linting
> same as [turf-www => **lintAPI**](https://github.com/Turfjs/turf-www/blob/gh-pages/package.json#L11)
- [x] Drop this testing in [`turf-www`](https://github.com/Turfjs/turf-www)
> the turf-www repo will only focus on building the website and not be used for validation or linting

This was suppose to be a PR and not pushed directly to master "Commit https://github.com/Turfjs/turf/commit/46756c2604852d9f19e123183c799cd20eeaf491" (thought I disabled that - guess not 😝)

CC: @stebogit @rowanwins @tmcw @morganherlocker

**Comment by stebogit** [comment]
>the turf-www repo will only focus on building the website and not be used for validation or linting

👍 👍  @DenisCarriere

**Comment by stebogit** [comment]
> - [ ] Add DocumentationJS linting

@DenisCarriere should I just add
```json
 "lintAPI": "documentation lint turf/packages/turf-*/index.js",
```
[`turf/package.json`](https://github.com/Turfjs/turf/blob/master/package.json)?

**Comment by DenisCarriere** [comment]
👍 We should include this documentation linting.

@stebogit we can also use the `post/pre` to run our scripts, this will chain the `npm` scripts.

```json
"lint": "eslint packages",
"postlint": "documentation lint packages/turf-*/index.js",
```
I'm getting warnings (which = as errors in TravisCI), but these seem pretty easy to fix.

```bash
$ npm run lint

> @4.0.0 lint /Users/mac/Github/turf
> eslint packages


> @4.0.0 postlint /Users/mac/Github/turf
> documentation lint packages/turf-*/index.js

/Users/mac/Github/turf/packages/turf-bbox-polygon/index.js
        9:1  warning  unknown tag @addToMap

/Users/mac/Github/turf/packages/turf-boolean-contains/index.js
      220:1  warning  type Boolean found, boolean is standard

/Users/mac/Github/turf/packages/turf-boolean-crosses/index.js
      146:1  warning  type Boolean found, boolean is standard

/Users/mac/Github/turf/packages/turf-boolean-point-on-line/index.js
       38:1  warning  type String found, string is standard

/Users/mac/Github/turf/packages/turf-meta/index.js
      468:1  warning  type object found, Object is standard
      741:1  warning  unknown tag @turf
      760:1  warning  unknown tag @turf

/Users/mac/Github/turf/packages/turf-square/index.js
       10:1  warning  unknown tag @addToMap

⚠ 8 warnings
```

**Comment by DenisCarriere** [comment]
Finally dropped all tests & linting from `turf-www` since it's implemented directly in TurfJS.
